name: datacraft-website

services:
  website:
    image: datacraft-website:production

    restart: unless-stopped

    networks:
      proxy:
        aliases:
          - datacraft-website

networks:
  proxy:
    external: true
    name: datacraft_proxy
